### ISSUE TITLE
not working in 2.1.0

### ISSUE THREAD

**Issue by stuee147** [Ghost-chu/QuickShop-Reremake#126]
hi for some reason all shops made before the update dont work they have just become normal chests but still have the signs on.
new chests seem to work fine at the moment 

server running 1.14.2

**Comment by Ghost-chu** [comment]
More details?
QS Paste, shops.db?

**Comment by Ghost-chu** [comment]
try 2.1.1

**Comment by stuee147** [comment]
hi 
sorry for the delay in replying i tried 2.1.1 and still no difference all old shops dont work.
here are the files you asked for i hope they help
[server36940 - 19 Jun 2019 13_17_51.zip](https://github.com/Ghost-chu/QuickShop-Reremake/files/3306015/server36940.-.19.Jun.2019.13_17_51.zip)

**Comment by Ghost-chu** [comment]
It looks your database is dead, it may caused by force server shutdown, accident unplugged AC power, system crashed.

Sorry but it can't be fix, the database already gone, the data can't restore.

Delete shops.db to let plugin re-create a new database.

An advice is use MySQL or shutdown the server by /stop command.

**Comment by stuee147** [comment]
Thanks for your help I have remade the shops and it seems to be working well again
