### ISSUE TITLE
Eng lang broken

### ISSUE THREAD

**Issue by SkeletonAce** [Ghost-chu/QuickShop-Reremake#1537]
### Description

My customised messages for shops and in chat messages are erased with the most recent update,
Shop are also all showing out of stock.

### Steps to reproduce

update to 5.0.0.3

### Expected Behaviour

I have custom message colours set up

### Screenshots

![2021-11-01_10 43 01](https://user-images.githubusercontent.com/76664499/139602157-311e2242-605b-4df8-a91d-e12457e1ebc0.png)

### `/qs paste` URL

paste-6e60b698cf9d406d8b562a7b475f2490.txt

**Comment by Andre601** [comment]
I have a similar, yet different issue.

In my case are signs showing 2nd and 3rd line in white while using NBT API and right-clicking the signs...
Not sure if the white text is a new, intentional change or if that is just a possible downside of NBT API, but it's a bit annoying.

![2021-10-31_23 14 57](https://user-images.githubusercontent.com/11576465/139603009-9daabb6a-4d9d-454d-8adb-8373f4e87801.png)

**Comment by Ghost-chu** [comment]
quickshop use new messages system, old messages.json no longer works.

**Comment by Ghost-chu** [comment]
white text not should be a part of the sign, i will check them, thanks for reporting

**Comment by sandtechnology** [comment]
> 
> 
> quickshop use new messages system, old messages.json no longer works.

Should we write an auto-migrate system for message.json? since it's logic and file structure is very similar

**Comment by Ghost-chu** [comment]
@Andre601 @SkeletonAce 
This build should fixed strange white color:
https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/1909/artifact/target/QuickShop.jar

For the Out Of Stock issue, I need more details. Please upload the paste.
