### ISSUE TITLE
[Feature] Armorstand display better rotation

### ISSUE THREAD

**Issue by LoneDev6** [Ghost-chu/QuickShop-Reremake#162]
Please can you look into this issue? Some items are shown in strange rotation:

Netherwart
![image](https://user-images.githubusercontent.com/27242001/62430432-ecb89d80-b71c-11e9-9de9-aa2d51b39890.png)

Bow
![image](https://user-images.githubusercontent.com/27242001/62430440-fb9f5000-b71c-11e9-9666-f841c2da6c1f.png)

Sugar cane
![image](https://user-images.githubusercontent.com/27242001/62430448-0fe34d00-b71d-11e9-940f-6691ac262b14.png)

and more

**Comment by Vlvxingze** [comment]
I received,it will be fixed in 24 hours

**Comment by LoneDev6** [comment]
Thanks!

**Comment by Ghost-chu** [comment]
Delay notice: The developer @Vlvxingze 's home got some trouble, so this issue maybe will delay to fix, sorry for that.

**Comment by LoneDev6** [comment]
Any news? :D

**Comment by Vlvxingze** [comment]
Acually,I just test,
Torch and more items also have this problem
In fact,I don't know how to solve this.
I think I cann't test every item to fix this problem.
,,,Maybe need more time,but I will try

**Comment by LoneDev6** [comment]
You could use small armorstand with helmet, that will fix

**Comment by LoneDev6** [comment]
![immagine](https://user-images.githubusercontent.com/27242001/63132669-56a93080-bfc2-11e9-9d5b-cf114d1fb631.png)

**Comment by Ghost-chu** [comment]
Cool, that's a good idea.
@Vlvxingze

**Comment by LoneDev6** [comment]
It will resolve all the issues surely!
It may result bugged if the player edited some special hats using resourcepack, but should not be a real issue.. maybe would be cool to add a list of item material/display name/nbt tag (CustomModelData) to chose which time of display to use:
- UNKNOWN(-1), 
- REALITEM(0), 
- ARMORSTAND(1), 
- **ARMORSTAND_SMALL(2),** 
- VIRTUALITEM(**3**)

**Comment by LoneDev6** [comment]
Any news on the eta?

**Comment by Ghost-chu** [comment]
This issue completely need waiting @Vlvxingze finish it.

**Comment by cakoyo** [comment]
@LoneDev6 @Ghost-chu @Vlvxingze 
I believe this will be fixed soon, but no eta.
I have looked into that and I found the reason to cause this issue is that the item is in a different position when armour stand/player hold them (such as Torch is in the back of the head and some is on the top, some as a mask), and this happens on both hand slot and helmet slot. This is seriously an obstacle and I don't have a very clear idea to resolve it.
The original implementation is put items into the hand slot, however, there are mistakes with the location setting, which is root the reason to cause the issue above as the item display is in wrongly offset like one block away. I already resolve it by doing some research between block face and yaw, so the first problem matters.
As it is, we have to find a way to identify the exactly pose that item will be applied when they are in armour stand, and then to adjust the angle and the height, etc.
For your information, the direction of some blocks provided by API is wrong somehow, such as anvil and fence, it is also what we should care about.

**Comment by LoneDev6** [comment]
> 
> 
> It will resolve all the issues surely!
> It may result bugged if the player edited some special hats using resourcepack, but should not be a real issue.. maybe would be cool to add a list of item material/display name/nbt tag (CustomModelData) to chose which time of display to use:
> 
>     * UNKNOWN(-1),
> 
>     * REALITEM(0),
> 
>     * ARMORSTAND(1),
> 
>     * _**ARMORSTAND_SMALL(2),**_
> 
>     * VIRTUALITEM(_**3**_)

as I said here there is a big problem with resourcepacks that add hats and wings, they will be better to be shown on hand instead of head

**Comment by cakoyo** [comment]
@LoneDev6 I didn't get that, why it is better to be shown on hand?
Also, I will add the ability to let the user modify more display details (angle, height), would that solve the issue?

**Comment by LoneDev6** [comment]
I need to be able to chose if I want to show the item on **armorstand head** / **armorstand hand** / **item drop** and change the angle for each material.

As you can see I added wearables which are basically remodelled items when on head or on hand
https://www.youtube.com/watch?v=Wr9UuDPWAIg

**Comment by cakoyo** [comment]
@LoneDev6 ok, I will add all of them.

**Comment by LoneDev6** [comment]
Thanks a lot @cakoyo

**Comment by cakoyo** [comment]
Finished it, and a fixed list for item with a different angle in vanilla will be updated to config later.

**Comment by LoneDev6** [comment]
> 
> 
> Finished it, and a fixed list for item with a different angle in vanilla will be updated to config later.

Thanks!
I wait for examples on the config file

**Comment by cakoyo** [comment]
@LoneDev6 Done that, a default config is in the latest build.

**Comment by LoneDev6** [comment]
@cakoyo  Thanks a lot! Good work :D
I wait Ghost-chu to publish the new .jar file

**Comment by cakoyo** [comment]
@LoneDev6 You have to wait for a while, cause the commits were reverted due to maintaince-breaking.

**Comment by LoneDev6** [comment]
> 
> 
> @LoneDev6 You have to wait for a while, cause the commits were reverted due to maintenance-breaking.

No problem, I will wait
