### ISSUE TITLE
[BUG] When admin shop is buying shulker boxes, it gives player money but does not take the shulker from player's inventory.

### ISSUE THREAD

**Issue by Dudenn** [Ghost-chu/QuickShop-Reremake#200]
Description: When I went to sell shulker boxes to the Admin store, it would send me the message that I had just sold the shop an item (amount i sold, money I earned, taxes taken out), and I would receive the money, but the shulker box was not taken from my inventory. Upon further investigation, it appears that if the shulker box has ever been used before, the admin shop will not remove it from the players inventory, but go through the rest of the buy transaction of giving the player money. 

**This was not a problem before the most recent update.

I can provide screenshots if need be, and I can also provide support by looking over the code. If you have an idea where the problem in the code might be, just let me know and I'll take a look. Thanks!

**Comment by Jason897759** [comment]
I've looked at the bug and the problem seems to be nbt tags. If an item has an nbt tag it will not be removed, but you still receive the money.

**Comment by Dudenn** [comment]
So basically I can change the name of any item, and then sell that item to an admin shop, and will get the money but not lose the item... When will this be fixed??

**Comment by Dudenn** [comment]
I didn't realize there was already a setting that made this possible (see config.yml for a setting called "strict-matches-check"). That setting is set to "false" by default, I suggest changing it to be "true" by default. If the setting is unknown to server operators or a new config is generated and the setting is forgotten about, it can be abused very badly by players. Just my opinion, but I always err on the side of caution when it comes to these config settings.

**Comment by Jason897-SC** [comment]
But if you set it true you cant sell items with an nbt tag. As example a shulker box which was placed cant be sold.

**Comment by Ghost-chu** [comment]
Just update the plugin, it should already fixed in latest version.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jason"<notifications@github.com&gt;; 
发送时间: 2019年10月26日(星期六) 晚上9:38
收件人: "Ghost-chu/QuickShop-Reremake"<QuickShop-Reremake@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: Re: [Ghost-chu/QuickShop-Reremake] [BUG] When admin shop is buying shulker boxes, it gives player money but does not take the shulker from player&#39;s inventory. (#200)




But if you set it true you cant sell items with an nbt tag. As example a shulker box which was placed cant be sold.
 
&mdash;

**Comment by Ghost-chu** [comment]
Can you test which one version(release) is works fine?
You can find all released version in https://github.com/Ghost-chu/QuickShop-Reremake/releases.
The final jar name `QuickShop-Reremake.x.x.x.x.jar`
