### ISSUE TITLE
[BUG]Items will not be deducted

### ISSUE THREAD

**Issue by Longcg** [Ghost-chu/QuickShop-Reremake#201]
**Describe the bug**
If there is a purchase of a gold ingot store, I use mucus technology for sale. Then the item will not be replaced and the item name will be colored. The background will also report an error, players use this to brush money.(如果有一个收购原版金锭的商店，我使用粘液科技的物品[是金锭，但是名字不一样的“发泡锭”]出售。那么背包内的粘液科技物品不会被收走，但是会提示出售成功并且增加游戏币。后台也会报错，玩家利用这个刷钱。)

**Expected behavior**
I hope that it is best to remind you that there is no "gold ingot" in your backpack, instead of selling two different things at the same time.(我希望最好提示你背包内没有“金锭”，而不是可以同时出售两个不一的东西。)

**Paste link:**
 Execute command /qs paste, you will got a link contains your server infomations, paste it under this text.
[paste-925d754212094046bf9207e038b37615.txt](https://github.com/Ghost-chu/QuickShop-Reremake/files/3775746/paste-925d754212094046bf9207e038b37615.txt)

**Additional context**

**Comment by Ghost-chu** [comment]
Thanks for reporting, i will check them in this weekend.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Longcg"<notifications@github.com&gt;; 
发送时间: 2019年10月27日(星期天) 晚上7:14
收件人: "Ghost-chu/QuickShop-Reremake"<QuickShop-Reremake@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [Ghost-chu/QuickShop-Reremake] [BUG]Items will not be deducted (#201)




Describe the bug
 If there is a purchase of a gold ingot store, I use mucus technology for sale. Then the item will not be replaced and the item name will be colored. The background will also report an error, players use this to brush money.(如果有一个收购原版金锭的商店，我使用粘液科技的物品[是金锭，但是名字不一样的“发泡锭”]出售。那么背包内的粘液科技物品不会被收走，但是会提示出售成功并且增加游戏币。后台也会报错，玩家利用这个刷钱。)
 
Expected behavior
 I hope that it is best to remind you that there is no "gold ingot" in your backpack, instead of selling two different things at the same time.(我希望最好提示你背包内没有“金锭”，而不是可以同时出售两个不一的东西。)
 
Paste link:
 Execute command /qs paste, you will got a link contains your server infomations, paste it under this text.
 paste-925d754212094046bf9207e038b37615.txt
 
Additional context
 Add any other context about the problem here.

**Comment by Ghost-chu** [comment]
duplicate #200
