### ISSUE TITLE
[BUG] qs.log stay empty

### ISSUE THREAD

**Issue by Ectabro** [Ghost-chu/QuickShop-Reremake#207]
**Describe the bug**
Hello, my server run 1.14.4, i have the latest release of QSRR 2.4.7 and when player buy, sell or create shop, nothing is write into that file.

**To Reproduce**
Not so much step to reproduce it... I also try a clean install of QSRR, new database and new config, nothing changed

I hope i'm not the only one with this bug, because i need log for an addon i made for my server economy

**Comment by Ghost-chu** [comment]
It looks is a bug, i will fix it, thanks for reporting!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ectabro"<notifications@github.com&gt;; 
发送时间: 2019年11月13日(星期三) 凌晨1:57
收件人: "Ghost-chu/QuickShop-Reremake"<QuickShop-Reremake@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [Ghost-chu/QuickShop-Reremake] [BUG] qs.log stay empty (#207)




Describe the bug
 Hello, my server run 1.14.4, i have the latest release of QSRR 2.4.7 and when player buy, sell or create shop, nothing is write into that file.
 
To Reproduce
 Steps to reproduce the behavior:
 Not so much step to reproduce it... I also try a clean install of QSRR, new database and new config, nothing changed
 
I hope i'm not the only one with this bug, because i need log for an addon i made for my server economy

**Comment by Ectabro** [comment]
Problem is fixed, but is it normal that log don't show item name on it ?

For example i show you what is wrote on my log..

"purchased AdminShop shop item x1 for 200.00 Ducats (0.00 Ducats tax)."

Thanks for fast fix last time !
