### ISSUE TITLE
[PERFORMANCE] Random TPS Drop, please fix

### ISSUE THREAD

**Issue by LoneDev6** [Ghost-chu/QuickShop-Reremake#261]
**Describe the issue**
Lag, TPS drop

**To Reproduce**
I don't know, I just leave the server on with no players online. Also happens if players are online.
No one is using quickshop chests or doing anything, lag is there anyway..

**Expected behavior**
No lag, no tps drop.

**Screenshots**
![immagine](https://user-images.githubusercontent.com/27242001/71101340-cf113f80-21b6-11ea-9ef7-615840a848f7.png)

**Timings link:**
 Execute command /timings on to enable timings and wait for 10mins, then execute /timings paste to get timings link.
- https://timings.aikar.co/?id=1ec3b17a01a84df0984fc021441733f8

**Comment by Ghost-chu** [comment]
Require Spark performance report, please install Spark and use `/spark sampler --start` to start sampler. And execute `/spark sampler --stop` to create a sampler report link using Spark.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "LoneDev"<notifications@github.com&gt;; 
发送时间: 2019年12月18日(星期三) 晚上11:53
收件人: "Ghost-chu/QuickShop-Reremake"<QuickShop-Reremake@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [Ghost-chu/QuickShop-Reremake] [PERFORMANCE] Random TPS Drop, please fix (#261)




Describe the issue
 Lag, TPS drop
 
To Reproduce
 Steps to reproduce the behavior:
 I don't know, I just leave the server on with no players online. Also happens if players are online.
 
Expected behavior
 No lag, no tps drop.
 
Screenshots
 If applicable, add screenshots to help explain your problem.
 
 
Timings link:
 Execute command /timings on to enable timings and wait for 10mins, then execute /timings paste to get timings link.
  
https://timings.aikar.co/?id=1ec3b17a01a84df0984fc021441733f8
