### ISSUE TITLE
[PERFORMANCE] Wanna know how can i solve lag

### ISSUE THREAD

**Issue by diegolala666** [Ghost-chu/QuickShop-Reremake#310]
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  
README BEFORE REPORTING:  
Don't upload timings, we only accept Spark sampler result. If you issue not upload spark sampler result, you issue will closed without any reply.  
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  

**Describe the issue**
I think i'm having lag with QuickShop. Paper 1.15.1

**Expected behavior**
Help to change any config or something?

**Paste link:**
 Execute command /qs paste, you will get a link contains your server information, paste it under this text.
 You must create a paste, except plugin completely won't work.
 If you create failed, you should find a paste file under the plugin/QuickShop folder.
- https://paste.enginehub.org/yvm2OXvU

**Spark result link: (Require)**
 Install the spark at https://www.spigotmc.org/resources/spark.57242/, and execute /spark sampler --start to enable the spark sampler, wait 10mins and execute /spark sampler --stop to get sample result.
- https://sparkprofiler.github.io/#DN49m6F57a

**Additional context**
Timings: https://timings.aikar.co/?id=d946f7b0c90548799a0c6ee37d50053d

**Comment by Ghost-chu** [comment]
Cannot find any possible lagg, your server and plugin is healthy!
In timings yellow number that caused by loading possible shops from memory.
It only runed 8 times in sampling, won't effect server performance.

The most time cost on calling bukkit api, the api performance is decided by Minecraft Server performace, nothing we can do.

In 623884ms, quickshop only tooked 4ms, don't worry, it won't effect yoir server.
