### ISSUE TITLE
关于参与QuickShop-Reremake开发的一些问题

### ISSUE THREAD

**Issue by apachezy** [Ghost-chu/QuickShop-Reremake#317]
我是一名mc腐竹，并且熟悉java编程语言，愿意参与QuickShop-Reremake的开发，有一些问题想咨询：
1. 这个项目的代码风格之前一直使用四个空格的缩进，但前几天突然变成了两个空格。如果要参与开发，必须遵循这个代码风格吗？
2. 我可以对代码进行简化吗？例如：
  1) 目前的权限管理器完全没有必要，因为它只实现了一个判断玩家有无权限的功能。
  2) ItemStack的序列化和反序列化已经被YamlConfiguration实现了，再去实现完全没有必要。

以上，盼回复。如果参与开发还有其他约束条件，或者我的想法不能被接受，请告知，谢谢。

**Comment by cakoyo** [comment]
1) @Ghost-chu decided to switch to the Google style a few days ago, and it is the new standard for the project. Sure, developers have to follow that.
2) Sure, in my opinion, but you have to keep the compatibility (if it is an API) and improve it (instead of making it worse). That improves can be various, such as code clarity, performance, feature. And ensuring the old format will be transformed (without data loss) into the new one if you change the data format.
3) I am only a co-worker, please await a reply from Ghostchu.

**Comment by Ghost-chu** [comment]
感谢您有意愿参与QuickShop开发。

这个项目的代码风格之前一直使用四个空格的缩进，但前几天突然变成了两个空格。如果要参与开发，必须遵循这个代码风格吗？

> 我可以对代码进行简化吗？例如：
目前的权限管理器完全没有必要，因为它只实现了一个判断玩家有无权限的功能。

权限管理器实际上实现了一个灵活的接口，允许在未来对权限相关组件进行拓展。例如通过支持的权限插件来检查权限组，这个操作是普通hasPermission无法做到的，通常来说QS项目内没有需要精简的代码。有的话我一般会第一时间删掉。**别相信IDEA的无用代码和private建议，有些混在里面的属于API**

> ItemStack的序列化和反序列化已经被YamlConfiguration实现了，再去实现完全没有必要。

QS在反序列化之前会对ItemStack的版本号检查，当检查到服务端无法加载此ItemStack时向用户发出警告，或者允许用户通过修改原文本中的版本号欺骗服务端加载，尽可能减少用户因升级降级导致的数据库无法再被读取问题。

我们一直都允许所有人参与开发，但对于对新QS架构不熟悉的开发者，我们推荐使用PullRequest的形式实现。
