### ISSUE TITLE
[BUG] /qs dize don't work

### ISSUE THREAD

**Issue by VeteranDrenor** [Ghost-chu/QuickShop-Reremake#453]
Hello,
After creating a shop, we can't use the /qs size to change how many items are sells.
For exemple, we do /qs size 6 and the plugins show the command list
I use the latest version of the plugins (4.0.2.5) on spigot 1.14.4 (the latest)
I have no errors on my serveur consol.

Thanks you for your help !

**Comment by Ghost-chu** [comment]
Enable allow-stacks option

**Comment by MrAmos123** [comment]
Maybe make this apparent by removing the UI element or writing "For this feature enable it in the config" in-game.

It seems really dumb to just leave it there with no function at all. Making the user wonder if it's broken.

**Comment by MrAmos123** [comment]
Also... I just enabled `allow-stacks` in the config and reloaded. The `/qs size [Amount]` still doesn't work...

**Comment by MrAmos123** [comment]
Whilst I'm here... Remove the [Amount] placeholders. it confuses people who don't understand placeholders.

Just leave the command open. 

https://i.imgur.com/LJFow17.png

**Comment by MrAmos123** [comment]
@Ghost-chu

**Comment by sandtechnology** [comment]
> 
> 
> Whilst I'm here... Remove the [Amount] placeholders. it confuses people who don't understand placeholders.
> 
> Just leave the command open.
> 
> https://i.imgur.com/LJFow17.png

you should open an new issue or just talk all of this in discord channel.
And let me answer those question one by one:
1. I change this already recently, now the option will hide when disabled:https://github.com/Ghost-chu/QuickShop-Reremake/commit/f9275124f2043a081ee72569805cb0f1e22e222d
2. We even not using `display-allow-stacks` option in our code, I don't know why it isn't work.
3. I will remove those placeholders, since it will show on the top when you enter command.
